### ISSUE TITLE
After creating the account, click the "login button" and there is no response.

### ISSUE THREAD

**Issue by YEDEDD** [haishanh/cherry#10]
After my docker-compose was created, the input account number and clicking the login button did not respond.

docker-compose file:
```
version: '3'

services:
  cherry:
    image: haishanh/cherry:v0.0.3
    container_name: cherry
    restart: unless-stopped
    ports:
      - 5150:8000
    volumes:
      - /data/cherry/data:/data
    environment:
      - JWT_SECRET=some-some-secret-string
      - ENABLE_PUBLIC_REGISTRATION=1
```

**Comment by tiritibambix** [comment]
Use a reverse proxy with ssl or use the variable ```USE_INSECURE_COOKIE```

**Comment by Tataukee** [comment]
USE_INSECURE_COOKIE = ?

**Comment by Tataukee** [comment]
USE_INSECURE_COOKIE = true ?

**Comment by tiritibambix** [comment]
https://cherry.haishan.me/docs/deploy#environment-variables

**Comment by Tataukee** [comment]
Thanks a lot @tiritibambix and @YEDEDD for posting the same issue i was experiencing 
I confirm the login is successful after adding the variable : 
USE_INSECURE_COOKIE = 1

**Comment by YEDEDD** [comment]
@haishanh @Tataukee @tiritibambix Thank you for your answers. I tried to add the environment variable "USE_INSECURE_COOKIE = 1" but still did not respond and cleaned up the browser cache.
docker-compose file:
```
version: '3'

services:
  cherry:
    image: haishanh/cherry
    container_name: cherry
    restart: unless-stopped
    ports:
      - 5151:8000
    volumes:
      - /data/cherry/data:/data
    environment:
      - JWT_SECRET=some-some-secret-string
      - USE_INSECURE_COOKIE = 1
 ```
