### ISSUE TITLE
Docker Compose without caddy and authelia

### ISSUE THREAD

**Issue by rivolity** [haishanh/cherry#27]
Hello,
I have executed the following docker compose

```
---
version: '3.3'

services:
  cherry:
    image: haishanh/cherry:test
    container_name: auth_cherry
    volumes:
      - "/home/cherry:/data"
    environment:
      - JWT_SECRET=some-secret-string
      # this flag is important for remote-user feature to work
      - ENABLE_HTTP_REMOTE_USER=1
      - HTTP_REMOTE_USER_HEADER_NAME=Remote-User
    ports:
      - 8012:5173
```

When the docker is up, it requests a user and a password, which I can't find in your documentation.
What is the default user and password, so I can authenticate to the app.

<img src="https://user-images.githubusercontent.com/39197760/232090734-6c35f5c0-f533-46bb-866f-685d963d31c5.png" width="500">

**Comment by rivolity** [comment]
I've solved my probleme by using the latest image on the docker hub
```
---
version: '3.9'

services:
  cherry:
    image: haishanh/cherry:latest
    container_name: cherry
    volumes:
      - "/home/atay/docker/cherry:/data"
    environment:
      - JWT_SECRET="8M$QkASoNB4kLz"
      - ENABLE_PUBLIC_REGISTRATION=0
      - USE_INSECURE_COOKIE=1
    ports:
      - 8012:8000
```
